services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./front:/app
      - front_node_modules:/app/node_modules
    command: yarn dev -p 4000
    ports:
      - "4000:4000"
  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./back:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    container_name: db
    # dbサービスはDockerfileを持っていないので、ベースイメージを指定
    image: mysql:8.0
    # 環境変数
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
    # データベースの値を永続化
    volumes:
      - ./back/tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  front_node_modules:
