# == Schema Information
#
# Table name: stocks
#
#  id                                   :bigint           not null, primary key
#  age(年代)                            :integer          default(0), not null
#  alcohol_spray(アルコールスプレー)    :integer          default(0)
#  aluminum_foil(アルミホイル)          :integer          default(0)
#  baby_bottle(哺乳瓶)                  :integer          default(0)
#  baby_wipe(お尻ふき)                  :integer          default(0)
#  battery_charger(充電器)              :integer          default(0)
#  body_warmer(カイロ)                  :integer          default(0)
#  canned_fruits(果物の缶詰)            :integer          default(0)
#  confectionery(お菓子)                :integer          default(0)
#  contact_lenses(コンタクトレンズ)     :integer          default(0)
#  denture_cleaner(入れ歯洗浄剤)        :integer          default(0)
#  diaper(おむつ)                       :integer          default(0)
#  dry_cell_battery(乾電池)             :integer          default(0)
#  flashlight(懐中電灯)                 :integer          default(0)
#  gloves(軍手)                         :integer          default(0)
#  lighter(マッチ)                      :integer          default(0)
#  mask(マスク)                         :integer          default(0)
#  medicine(常備薬)                     :integer          default(0)
#  milk_powder(粉ミルク)                :integer          default(0)
#  newspaper(新聞紙)                    :integer          default(0)
#  nutritional_supplement(栄養補助食品) :integer          default(0)
#  plastic_bag(ポリ袋)                  :integer          default(0)
#  prescription_drug(処方箋薬)          :integer          default(0)
#  radio(ラジオ)                        :integer          default(0)
#  retort_food(レトルト食品)            :integer          default(0)
#  retort_rice(レトルトご飯)            :integer          default(0)
#  ruck_sack(リュックサック)            :integer          default(0)
#  sanitary_item(生理用品)              :integer          default(0)
#  sex(性別)                            :integer          default(0), not null
#  simple_toilet(簡易トイレ)            :integer          default(0)
#  tissue_paper(ティッシュペーパー)     :integer          default(0)
#  toilet_paper(トイレットペーパー)     :integer          default(0)
#  water(水)                            :integer          default(0)
#  water_supply_bag(給水袋)             :integer          default(0)
#  wet_wipes(ウェットティッシュ)        :integer          default(0)
#  wrap(ラップ)                         :integer          default(0)
#  created_at                           :datetime         not null
#  updated_at                           :datetime         not null
#
class Stock < ActiveHash::Base
  self.data = [
    {
      sex: 'Male',
      age: 'Infant',
      water: 8,
      retort_rice: 0,
      retort_food: 0,
      nutritional_supplement: 0,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 0,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 0,
      lighter: 1,
      body_warmer: 0,
      contact_lenses: 0,
      battery_charger: 0,
      gloves: 0,
      newspaper: 0,
      radio: 1,
      simple_toilet: 0,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 18,
      diaper: 30,
      baby_wipe: 3,
      baby_bottle: 18,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 男性、子供(3歳~小6)
      sex: 'Male',
      age: 'Child',
      water: 8,
      retort_rice: 8,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 男性、子供(中学生以上)
      sex: 'Male',
      age: 'Junior',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 男性、成人(20歳以上)
      sex: 'Male',
      age: 'Adult',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 男性、高齢者(65歳以上)
      sex: 'Male',
      age: 'Senior',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 90,
      prescription_drug: 1,
      ruck_sack: 1
    },
    {
      # 女性、乳幼児(0~2歳)
      sex: 'Female',
      age: 'Infant',
      water: 8,
      retort_rice: 0,
      retort_food: 0,
      nutritional_supplement: 0,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 0,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 0,
      lighter: 1,
      body_warmer: 0,
      contact_lenses: 0,
      battery_charger: 0,
      gloves: 0,
      newspaper: 0,
      radio: 1,
      simple_toilet: 0,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 18,
      diaper: 30,
      baby_wipe: 3,
      baby_bottle: 18,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 女性、子供(3歳~小6)
      sex: 'Female',
      age: 'Child',
      water: 8,
      retort_rice: 8,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 女性、子供(中学生以上)
      sex: 'Female',
      age: 'Junior',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 13,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 女性、成人(20歳以上)
      sex: 'Female',
      age: 'Adult',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 13,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 0,
      prescription_drug: 0,
      ruck_sack: 1
    },
    {
      # 女性、高齢者(65歳以上)
      sex: 'Female',
      age: 'Senior',
      water: 9,
      retort_rice: 9,
      retort_food: 3,
      nutritional_supplement: 3,
      confectionery: 3,
      canned_fruits: 3,
      wet_wipes: 30,
      alcohol_spray: 1,
      mask: 3,
      medicine: 1,
      wrap: 1,
      plastic_bag: 1,
      aluminum_foil: 1,
      toilet_paper: 2,
      tissue_paper: 2,
      flashlight: 1,
      dry_cell_battery: 1,
      lighter: 1,
      body_warmer: 6,
      contact_lenses: 1,
      battery_charger: 1,
      gloves: 3,
      newspaper: 1,
      radio: 1,
      simple_toilet: 15,
      water_supply_bag: 1,
      sanitary_item: 0,
      milk_powder: 0,
      diaper: 0,
      baby_wipe: 0,
      baby_bottle: 0,
      denture_cleaner: 90,
      prescription_drug: 1,
      ruck_sack: 1
    }
  ]
end
