# # 男性、乳幼児(0~2歳)
# Stock.create!(
#   id: 1,
#   sex: 1,
#   age: 1,
#   water: 17
#   retort_rice: 0
#   retort_food: 0
#   nutritional_supplement: 0
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 0
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 0
#   lighter: 1
#   body_warmer: 0
#   contact_lenses: 0
#   battery_charger: 0
#   gloves: 0
#   newspaper: 0
#   radio: 1
#   simple_toilet: 0
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 42
#   diaper: 70
#   baby_wipe: 7
#   baby_bottle: 42
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 男性、子供(3歳~小6)
# Stock.create!(
#   id: 2,
#   sex: 1,
#   age: 2,
#   water: 17
#   retort_rice: 17
#   retort_food: 6
#   nutritional_supplement: 6
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 男性、子供(中学生以上)
# Stock.create!(
#   id: 3,
#   sex: 1,
#   age: 3,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 男性、成人(20歳以上)
# Stock.create!(
#   id: 4,
#   sex: 1,
#   age: 4,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 男性、高齢者(65歳以上)
# Stock.create!(
#   id: 5,
#   sex: 1,
#   age: 5,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 210
#   prescription_drug: 1
#   ruck_sack: 1
# )

# # 女性、乳幼児(0~2歳)
# Stock.create!(
#   id: 6,
#   sex: 2,
#   age: 1,
#   water: 17
#   retort_rice: 0
#   retort_food: 0
#   nutritional_supplement: 0
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 0
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 0
#   lighter: 1
#   body_warmer: 0
#   contact_lenses: 0
#   battery_charger: 0
#   gloves: 0
#   newspaper: 0
#   radio: 1
#   simple_toilet: 0
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 42
#   diaper: 70
#   baby_wipe: 7
#   baby_bottle: 42
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 女性、子供(3歳~小6)
# Stock.create!(
#   id: 7,
#   sex: 2,
#   age: 2,
#   water: 17
#   retort_rice: 17
#   retort_food: 6
#   nutritional_supplement: 6
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 女性、子供(中学生以上)
# Stock.create!(
#   id: 8,
#   sex: 2,
#   age: 3,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 30
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 女性、成人(20歳以上)
# Stock.create!(
#   id: 9,
#   sex: 2,
#   age: 4,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 30
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 0
#   prescription_drug: 0
#   ruck_sack: 1
# )

# # 女性、高齢者(65歳以上)
# Stock.create!(
#   id: 10,
#   sex: 2,
#   age: 5,
#   water: 21
#   retort_rice: 21
#   retort_food: 7
#   nutritional_supplement: 7
#   confectionery: 7
#   canned_fruits: 7
#   wet_wipes: 70
#   alcohol_spray: 1
#   mask: 7
#   medicine: 1
#   wrap: 1
#   plastic_bag: 1
#   aluminum_foil: 1
#   toilet_paper: 3
#   tissue_paper: 3
#   flashlight: 1
#   dry_cell_battery: 1
#   lighter: 1
#   body_warmer: 14
#   contact_lenses: 1
#   battery_charger: 1
#   gloves: 7
#   newspaper: 1
#   radio: 1
#   simple_toilet: 35
#   water_supply_bag: 1
#   sanitary_item: 0
#   milk_powder: 0
#   diaper: 0
#   baby_wipe: 0
#   baby_bottle: 0
#   denture_cleaner: 210
#   prescription_drug: 1
#   ruck_sack: 1
# )
